/** Kinds of tool links ("slots") tabs can show. Kept in its own small file so pages can use the names without the link editor. */
export const TOOL_SLOT_LABELS: Record<string, string> = {
  team_chat: 'Team chat',
  portfolio: 'Portfolio doc',
  code_repo: 'Code repository',
  cad: 'CAD (Onshape)',
  drive: 'Shared Drive folder',
  website: 'Team website',
  social: 'Social media',
  ftcscout: 'FTCScout team page',
  manual: 'Competition manual',
  gm0: 'Game Manual 0',
  ftc_docs: 'FTC Docs',
  qa_forum: 'Rules Q&A forum',
  scouting_sheet: 'Scouting sheet',
  printer_dashboard: 'Printer dashboard',
  outreach_doc: 'Outreach log doc',
  sdk_docs: 'SDK / library docs',
  other: 'Other',
};
