/** Regenerates docs/modules/README.md from the module manifests: `npm run docs:modules`. */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { MODULE_CATEGORIES } from '@teamhub/config-schema';
import { loadCatalog, REPO_ROOT } from '@teamhub/generator';

const LABEL: Record<string, string> = { team: 'Team', engineering: 'Engineering', competition: 'Competition', outreach: 'Outreach & Business' };
const c = await loadCatalog();
const lines = [
  '# Tab library',
  '',
  `TeamHub ships ${c.modules.size} optional tabs. Pick any combination in the setup wizard; tabs you don't pick add **zero bytes** to`,
  'your site and **zero tables** to your database. Each tab has one clear purpose and says what it is *not* for, so',
  'features never overlap.',
  '',
  '<!-- Generated by `npm run docs:modules` — edit the module manifests and READMEs instead. -->',
  '',
];
for (const cat of MODULE_CATEGORIES) {
  const mods = [...c.modules.values()].filter((m) => m.manifest.category === cat).sort((a, b) => a.manifest.name.localeCompare(b.manifest.name));
  if (!mods.length) continue;
  lines.push(`## ${LABEL[cat]}`, '', '| Tab | Purpose | Not for | Stores | Uses files | Prefix |', '|---|---|---|---|---|---|');
  for (const m of mods) {
    const x = m.manifest;
    const notFor = x.notFor.map((n) => n.text).join('; ');
    lines.push(`| [${x.name}](../../modules/${x.id}/README.md) | ${x.purpose} | ${notFor} | ${x.stores ?? ''} | ${x.usesFiles ? 'Yes' : ''} | \`${x.prefix}\` |`);
  }
  lines.push('');
}
lines.push('“Uses files” tabs store compressed uploads in Supabase Storage (see the Admin > Storage meter).', '');
lines.push('## Integrations', '', 'Small units that switch on automatically when both tabs are enabled:', '', '| Integration | What it adds |', '|---|---|');
for (const i of [...c.integrations.values()].sort((a, b) => a.manifest.id.localeCompare(b.manifest.id))) lines.push(`| \`${i.manifest.id}\` | ${i.manifest.summary} |`);
lines.push('');
writeFileSync(join(REPO_ROOT, 'docs/modules/README.md'), lines.join('\n'));
console.log('Wrote docs/modules/README.md');
